language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ia32-libs
  - sudo apt-get -f -y install

script: gradle clean build jarDistZip exeDistZip createAppZip renameFiles