language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ia32-libs-multiarch
  - sudo apt-get install -y ia32-libs

script: gradle clean build jarDistZip exeDistZip createAppZip renameFiles