language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -f -y install
  - sudo apt-get install -y libgphoto2-2
  - sudo apt-get install -y libsane
  - sudo apt-get install -y ia32-libs-multiarch
  - sudo apt-get install -y ia32-libs

script: gradle clean build jarDistZip exeDistZip createAppZip renameFiles